### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by robrich82** [FransUrbo/Lambda-AWS-AutoScalingGroups-Route53#3]
I'm very happy someone is doing this, however, I am unclear how to set this up now, it looks more complicated than the original design?

**Comment by FransUrbo** [comment]
It's done pretty much the same way. You'll need a RedisDB though. But yes, it's quite a lot more complicated :(. For the added functionality though :).

I haven't had time to write a setup guide unfortunately, but I would very much appreciate one.

**Comment by robrich82** [comment]
Ok, so I think I figured out most of it, once I realised what Terraform was and how it worked.

However, everything seems great... except my Route 53 record doesn't get updated.

It may have been caused by the fact I altered it to use my existing VPC/Security Groups/Redis etc. but I'm not sure, it did seem to be reading everything correctly, just not updating.
